
import { getSwagger } from 'exp_swagger';

// Get autogenerated Swagger
const swagger_options = getSwagger({
    version : '1.0.0',
    title : 'Base Express TS',
    host : 'localhost:2010',
    description : 'Base Express Api Documentation',
});



export default swagger_options